version: "3.9"
services:
  
  backend:
    build: ./backend
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      prestart:
        condition: service_completed_successfully
  
  db:
    build: 
      context: ./databases
      dockerfile: postgresql.Dockerfile
    environment:
      - PGDATA=/var/lib/vector_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "54322:5432"
    volumes:
      - pgdata:/var/lib/vector_db
  
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
      - "3000:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
  
  prestart:
    build:
      context: ./backend
    networks:
      - default
    depends_on:
      db:
        condition: service_healthy
    command: bash /app/scripts/prestart.sh
    env_file:
      - .env
    environment:
      - DOMAIN=${DOMAIN}
      - FRONTEND_HOST=${FRONTEND_HOST?Variable not set}
      - ENVIRONMENT=${ENVIRONMENT}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
      - SECRET_KEY=${SECRET_KEY?Variable not set}
      - FIRST_SUPERUSER=${FIRST_SUPERUSER?Variable not set}
      - FIRST_SUPERUSER_PASSWORD=${FIRST_SUPERUSER_PASSWORD?Variable not set}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAILS_FROM_EMAIL=${EMAILS_FROM_EMAIL}
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
  db-init:
    image: postgres:15
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    command: >
      bash -c "
        until pg_isready -h db; do
          echo 'Waiting for db...'
          sleep 2
        done
        echo 'Database is ready!'
        psql -h db -U $POSTGRES_USER -d $POSTGRES_DB -c 'CREATE EXTENSION IF NOT EXISTS vector;'
        echo 'Extension installed (if it was missing).'
      "

volumes:
  pgdata:
